export const PROFILE_SCHEMA = "zmk-pointing-tools/tuning-profile";
export const PROFILE_VERSION = 1;

function asTargets(targets) {
  return targets instanceof Map ? [...targets.values()] : [...targets];
}

function requireMetadata(target) {
  if (!target.stableId || !target.devicetreePath) {
    throw new Error(`${target.label} is missing stable profile metadata`);
  }
  for (const parameter of target.parameters) {
    if (!parameter.key || !parameter.devicetreeProperty) {
      throw new Error(`${target.label} / ${parameter.label} is missing stable profile metadata`);
    }
  }
}

export function createTuningProfile(targets, exportedAt = new Date().toISOString()) {
  const available = asTargets(targets);
  for (const target of available) requireMetadata(target);
  return {
    schema: PROFILE_SCHEMA,
    version: PROFILE_VERSION,
    exportedAt,
    targets: available.map((target) => ({
      stableId: target.stableId,
      kind: target.kind,
      label: target.label,
      devicetreePath: target.devicetreePath,
      parameters: target.parameters.map((parameter) => ({
        key: parameter.key,
        devicetreeProperty: parameter.devicetreeProperty,
        value: parameter.current,
        compiled: parameter.compiled,
      })),
    })),
  };
}

export function prepareProfileImport(profile, targets) {
  if (profile?.schema !== PROFILE_SCHEMA || profile?.version !== PROFILE_VERSION ||
      !Array.isArray(profile.targets)) {
    throw new Error("Unsupported or malformed tuning profile");
  }

  const available = asTargets(targets);
  for (const target of available) requireMetadata(target);
  const byStableId = new Map(available.map((target) => [target.stableId, target]));
  const seenTargets = new Set();
  const errors = [];
  const batches = [];

  for (const profileTarget of profile.targets) {
    if (!profileTarget || typeof profileTarget.stableId !== "string" ||
        !Array.isArray(profileTarget.parameters)) {
      errors.push("Profile contains a malformed target");
      continue;
    }
    if (seenTargets.has(profileTarget.stableId)) {
      errors.push(`Duplicate target ${profileTarget.stableId}`);
      continue;
    }
    seenTargets.add(profileTarget.stableId);

    const target = byStableId.get(profileTarget.stableId);
    if (!target) {
      errors.push(`Unknown target ${profileTarget.stableId}`);
      continue;
    }
    if (profileTarget.kind !== target.kind) {
      errors.push(`Target kind mismatch for ${profileTarget.stableId}`);
      continue;
    }

    const byKey = new Map(target.parameters.map((parameter) => [parameter.key, parameter]));
    const seenParameters = new Set();
    const values = [];
    for (const profileParameter of profileTarget.parameters) {
      const key = profileParameter?.key;
      if (typeof key !== "string") {
        errors.push(`Malformed parameter in ${profileTarget.stableId}`);
        continue;
      }
      if (seenParameters.has(key)) {
        errors.push(`Duplicate parameter ${profileTarget.stableId}.${key}`);
        continue;
      }
      seenParameters.add(key);

      const parameter = byKey.get(key);
      if (!parameter) {
        errors.push(`Unknown parameter ${profileTarget.stableId}.${key}`);
        continue;
      }
      const value = profileParameter.value;
      if (!Number.isInteger(value) || value < parameter.minimum || value > parameter.maximum ||
          (value - parameter.minimum) % parameter.step !== 0 ||
          (parameter.type === 1 && value !== 0 && value !== 1)) {
        errors.push(`Invalid value for ${profileTarget.stableId}.${key}`);
        continue;
      }
      values.push({ parameterId: parameter.id, value });
    }
    if (values.length > 20) {
      errors.push(`Target ${profileTarget.stableId} exceeds the 20-value batch limit`);
    } else if (values.length > 0) {
      batches.push({ targetId: target.id, stableId: target.stableId, values });
    }
  }

  if (errors.length > 0) {
    throw new Error(errors.join("; "));
  }
  if (batches.length === 0) {
    throw new Error("Profile contains no applicable tuning values");
  }
  return batches;
}

export function renderDevicetreeSnippet(targets) {
  const available = asTargets(targets);
  for (const target of available) requireMetadata(target);

  const lines = [
    "/* Generated by ZMK Pointing Tools.",
    " * Review and commit these values to keep them as compiled defaults. */",
  ];
  for (const target of available) {
    lines.push("", `/* ${target.label} (${target.stableId}) */`, `&{${target.devicetreePath}} {`);
    for (const parameter of target.parameters) {
      if (parameter.type === 1) {
        lines.push(parameter.current
          ? `    ${parameter.devicetreeProperty};`
          : `    /delete-property/ ${parameter.devicetreeProperty};`);
      } else {
        lines.push(`    ${parameter.devicetreeProperty} = <${parameter.current}>;`);
      }
    }
    lines.push("};");
  }
  return `${lines.join("\n")}\n`;
}
