import test from "node:test";
import assert from "node:assert/strict";

import {
  PROFILE_SCHEMA,
  createTuningProfile,
  prepareProfileImport,
  renderDevicetreeSnippet,
} from "./profile.js";

const targets = [{
  id: 2,
  stableId: "left-scroll",
  kind: 1,
  label: "Left scroll",
  devicetreePath: "/zpt_left_scroll",
  parameters: [
    { id: 1, key: "scale-multiplier", devicetreeProperty: "scale-multiplier", type: 0, minimum: 1, maximum: 1024, step: 1, compiled: 7, current: 8, label: "Scale multiplier" },
    { id: 10, key: "discard-unclassified", devicetreeProperty: "discard-unclassified", type: 1, minimum: 0, maximum: 1, step: 1, compiled: 0, current: 0, label: "Discard" },
  ],
}];

test("exports stable, versioned profiles", () => {
  assert.deepEqual(createTuningProfile(targets, 4, "2026-01-01T00:00:00.000Z"), {
    schema: PROFILE_SCHEMA,
    version: 1,
    exportedAt: "2026-01-01T00:00:00.000Z",
    protocolVersion: 4,
    targets: [{
      stableId: "left-scroll",
      kind: 1,
      label: "Left scroll",
      devicetreePath: "/zpt_left_scroll",
      parameters: [
        { key: "scale-multiplier", devicetreeProperty: "scale-multiplier", value: 8, compiled: 7 },
        { key: "discard-unclassified", devicetreeProperty: "discard-unclassified", value: 0, compiled: 0 },
      ],
    }],
  });
});

test("prepares target-level atomic imports by stable keys", () => {
  const profile = createTuningProfile(targets, 4);
  profile.targets[0].parameters[0].value = 9;
  assert.deepEqual(prepareProfileImport(profile, targets), [{
    targetId: 2,
    stableId: "left-scroll",
    values: [{ parameterId: 1, value: 9 }, { parameterId: 10, value: 0 }],
  }]);
});

test("rejects unknown targets and parameters before applying anything", () => {
  const profile = createTuningProfile(targets, 4);
  profile.targets.push({ stableId: "missing", kind: 1, parameters: [] });
  profile.targets[0].parameters.push({ key: "unknown", value: 1 });
  assert.throws(() => prepareProfileImport(profile, targets), /Unknown parameter.*Unknown target/);
});

test("renders reviewable devicetree overlays", () => {
  assert.equal(renderDevicetreeSnippet(targets), `/* Generated by ZMK Pointing Tools.
 * Review and commit these values to keep them as compiled defaults. */

/* Left scroll (left-scroll) */
&{/zpt_left_scroll} {
    scale-multiplier = <8>;
    /delete-property/ discard-unclassified;
};
`);
});
